model:
  type: "gemma3"
  name: "google/gemma-3-4b-it"
  device: "auto"

tasks:
  - name: "segmentation_grounding_open_VQA_cot"
    data_path: "final_cot_v2/seg_grounding_open.tsv"

  - name: "segmentation_grounding_closed_VQA_cot"
    data_path: "final_cot_v2/seg_grounding_closed.tsv"

runtime:
  batch_size: 10
  max_new_tokens: 2048
  save_every: 50
  log_first_batch: true
  output_dir: "/pasteur/u/rdcunha/code/mmbu/results_cot_v3"